pythonProject3/demo project/movies/filmlist/urls.py
from django.contrib import admin
from django.urls import path, include

from movies.filmlist import views

app_name="filmlist"
urlpatterns = [
    # path('',views.home,name="home"),
    path('',views.movielistview.as_view(),name="home"),
    path('addfilm/',views.addfilm,name="addfilm"),
    path('viewdetails/<int:p>',views.viewdetails,name='viewdetails'),
    path('deletemovie/<int:p>',views.deletemovie,name='deletemovie'),
    path('editmovie/<int:p>',views.editmovie,name='editmovie'),
    ]

pythonProject3/demo project/movies/movies/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('filmlist.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject3/demo project/movies/filmlist/models.py
from django.db import models


class Movies(models.Model):
    title = models.CharField(max_length=30)
    year = models.IntegerField()
    rating = models.IntegerField()
    desc = models.CharField(max_length=50)
    img=models.ImageField(upload_to='film/img',null=True,blank=True)

pythonProject3/demo project/movies/filmlist/forms.py
from filmlist.models import Movies
from django import forms
# for creating builtin forms in template
class Movieform(forms.ModelForm):
    class Meta:
        model=Movies
        fields="__all__"

pythonProject3/demo project/movies/filmlist/views.py
from django.shortcuts import render


from movies.models import Movies
from movies.forms import Movieform
from django.views.generic import ListView
# from django.db.models import Q

# def home(request):
#     m = Movies.objects.all()
#     return render(request, 'home.html',{'m':m})

class movielistview(Listview):
    model=Movies
    template_name="home.html"
    context_objet_name="m"
def addfilm(request):
    if (request.method == "POST"):
        t = request.POST['t']
        y = request.POST['y']
        r = request.POST['r']
        d = request.POST['d']
        i = request.FILES['i']
        m = Movies.objects.create(title=t, year=y, rating=r, desc=d, img=i)
        m.save()
        return home(request)
    return render(request,'addfilm.html')

def viewdetails(request,p):
    m = Movies.objects.get(id=p)
    return render(request,'viewdetails.html',{'m':m})

def deletemovie(request,p):

    m = Movies.objects.get(id=p)
    m.delete()
    return home(request)

def editmovie(request,p):
    m = Movies.objects.get(id=p)
    form = Movieform(instance=m)
    if (request.method == "POST"):
        form = Movieform(request.POST,request.FILES,instance=m)

        if form.is_valid():
            form.save()
            return home(request)
    return render(request, 'editmovie.html', {'form': form})

pythonProject3/demo project/movies/templates/addfilm.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<h2>Add Film here</h2>
<form method="POST" class="p-4" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Title</label>
    <input type="text" class="form-control" name="t" placeholder="Enter Title">
  </div>
    <div class="mb-3">
    <label class="form-label">Year</label>
    <input type="number" class="form-control" name="y" placeholder="Enter year">
  </div>
    <div class="mb-3">
    <label class="form-label">Rating</label>
    <input type="number" class="form-control" name="r" placeholder="Enter rating">
  </div>
  <div class="mb-3">
    <label class="form-label">Description</label>
    <input type="text" class="form-control" name="d" placeholder="Enter Description">
  </div>
   <div class="mb-3">
    <label class="form-label">Image</label>
    <input type="file" class="form-control" name="i" placeholder="Enter image">
  </div>
    <div class="mb-3">
    <input type="submit" class="btn btn-primary">
  </div>


</form>
{% endblock %}

pythonProject3/demo project/movies/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
  </head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MOVIES</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'filmlist:home' %}">Home</a>
        </li>
      </ul>
       <div class="d-flex nav-item">
          <a class="btn btn-outline-success" href="{% url 'filmlist:addfilm' %}">ADD FILM</a>
        </div>

    </div>
  </div>
</nav>


<br>
{% block content %}
{% endblock %}


</body>
</html>

pythonProject3/demo project/movies/templates/editmovie.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<h2>Edit Movie</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<table>
    {{form.as_table}}
</table>
<input type="submit">
</form>
{% endblock%}

pythonProject3/demo project/movies/templates/home.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<h1>Movie List</h1>
<div class="container">
    <div class="row ">
        {%for i in m %}
        <div class=" col-md-3 " style="height:">
            <div class="card" style="height:">
                <img src="{{i.img.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body">
                 <h5 class="card-title" style="text-transform:uppercase;">{{i.title}}({{i.year}})</h5>
                    <p class="card-text">RATING:{{i.rating}}</p>
                <a href="{% url 'filmlist:viewdetails' i.id %}" class="btn btn-primary">VIEW</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

pythonProject3/demo project/movies/templates/viewdetails.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<h1>Movie Details</h1>
<br><br>
<!--<div class="container">-->
<!--    <div class="row">-->
<!--        <div class=" col-md-3 " >-->
<!--            <div class="card">-->
<!--                <img src="{{m.img.url}}" class="card-img-top" alt="..." height="250px">-->
<!--                <div class="card-body">-->
<!--                 <h5 class="card-title">{{m.title}}({{m.year}})</h5>-->
<!--                    <p class="card-text">RATING:{{m.rating}}</p>-->
<!--                    <p class="card-text">DESCRIPTION:{{m.desc}}</p>-->
<!--                <a href="{% url 'filmlist:editmovie' m.id %}" class="btn btn-warning">EDIT</a>-->
<!--                <a href="{% url 'filmlist:deletemovie' m.id %}" class="btn btn-danger">DELETE</a>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->


<div class="container">
    <div class="row">
        <div class=" col-md-6 " >
            <img src="{{m.img.url}}" class="img-top" alt="..." height="400px" width="500px">
        </div>
        <div class=" col-md-6 ">
            <h5 class="card-title" style="text-transform:uppercase;"><b>{{m.title}}({{m.year}})</b></h5><br>
                    <p class="card-text"><b>RATING:</b>{{m.rating}}</p>
                    <p class="card-text"><b>DESCRIPTION:</b><i>{{m.desc}}</i></p>
                <a href="{% url 'filmlist:editmovie' m.id %}" class="btn btn-warning">EDIT</a>
                <a href="{% url 'filmlist:deletemovie' m.id %}" class="btn btn-danger">DELETE</a>
        </div>

    </div>
</div>
{% endblock %}